### ISSUE TITLE
Getting error while configuring using vtk 8

### ISSUE THREAD

**Issue by narayanakvs** [Slicer/vtkAddon#16]
I am not able to configure the build using cmake when trying to do so using vtk 8. 

is there any specific version of vtk that is needed for the build?

**Comment by pieper** [comment]
vtkAddon builds with vtk 8 or 9 as part of the Slicer build process.  You can have a look there and if you are still having trouble post the specific error you are getting.

**Comment by jcfr** [comment]
> I am not able to configure the build using cmake when trying to do so using vtk 8.

Could you report here the exact version of VTK you are using and the corresponding build error ?

**Comment by jcfr** [comment]
Closing.

@narayanakvs  Do not hesitate to report a new issue if you are still having issues.
