### ISSUE TITLE
vtkWrapHierarchy is kept re-executed

### ISSUE THREAD

**Issue by lassoan** [Slicer/vtkAddon#22]
We experienced huge slowdowns of application builds due to vtkWrapHierarchy kept rebuilding hierarchy files. For example, Slicer build took 10 minutes when nothing changed.

It turned out that this was because VTK was updated after the application was built (which is very common on developer computers). This update updated the vtkWrapHierarchy.exe file's timestamp, which is a [dependency of hierarchy file generation build step](https://github.com/Slicer/vtkAddon/blob/5f040632f8222a71b1eb3564a10ae602bcaf5f94/CMake/vtkWrapHierarchy.cmake#L156-L160). Therefore it triggers rebuilding of hierarchy file. However, the content of the hierarchy file was not changed and therefore its timestamp remained the same (older than timestamp of vtkWrapHierarchy.exe). This means that next time the hierarchy got updated again.

One solution could be vtkWrapHierarchy.cmake should be updated to touch some timestamp file each time vtkWrapHierarchy.exe was executed and use that to determine if the target is up-to-date (rather than use the timestamp of the hierarchy file).

Another solution could be to force writing of hierarchy files (update their timestamp) even if the file has not changed. Currently, [vtkWrapHierarchy only updates the output hierarchy file if its content has changed](https://github.com/Kitware/VTK/blob/37102d559386dcec314775b7dfaa1b317f3b7d7e/Wrapping/Tools/vtkWrapHierarchy.c#L964).

**Workaround to speed up builds after a VTK update**: delete all the `*Hierarchy.txt` files (for example, in c:\D\S4R\Slicer-build).

**Comment by lassoan** [comment]
@jcfr is it usual for a compiler/generator to only update timestamp of the output file if the content is changed? I can see that it can save time, but it is the root cause of the unnecessary regeneration of the hierarchy files at every build.

**Comment by mathstuf** [comment]
It only works if the build graph executor uses something like file content hashes to trigger reexecution. Timestamp-based systems (which is all CMake supports today) will need to update timestamps to avoid problems like this.
