### ISSUE TITLE
Missing include file in vtkImageLabelDilate3D.cxx

### ISSUE THREAD

**Issue by southie** [Slicer/vtkAddon#45]
vtkImageLabelDilate3D.cxx added in #44 introduces a compilation error on Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.4 ; MSVC version 14.36.32532
Compilation fails with with error:
vtkAddon\vtkImageLabelDilate3D.cxx(67): error C2039: 'map': is not a member of 'std'

vtkComputeModeOfArray references std::map<T, int> but does not include the header <map> which results in the compilation error.
Reverting to the previous commit compiles as expected. Adding `#include <map>` to the includes also allows compilation to continue

**Comment by jcfr** [comment]
Thanks for the report. We will integrate a patch later in the day.

In the meantime, do not hesitate to propose a pull request.
